version: "3.9"

services:
  backend:
    build: ./backend
    container_name: kanban-backend
    ports:
      - "5174:5174"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: kanban-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5174/api
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: kanban-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kanban
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
